// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

/// Strings for the File optimizer page, and the Clipboard page's pointer to it.
/// The option labels themselves stay in `ClipboardImageOptimizerStrings`,
/// since both pages show the same controls.
struct FileOptimizerStrings {
    let title: String
    let hubDescription: String
    let pageCaption: String
    let dropPrompt: String
    let chooseFiles: String
    let queueHeader: String
    let cancelAll: String
    let clearFinished: String
    let reveal: String
    let cancel: String
    let queued: String
    let working: String
    let cancelled: String
    let failedFormat: String
    let sizeChangeFormat: String
    let savedFormat: String
    let outputHeader: String
    let outputMode: String
    let outputBeside: String
    let outputFolder: String
    let chooseFolder: String
    let noFolder: String
    let outputCaption: String
    let optionsHeader: String
    let optionsShared: String
    let imagesHeader: String
    let videosHeader: String
    let pdfsHeader: String
    let convertCaption: String
    let clipboardLink: String
    let openPage: String
    let notSmaller: String
    let tooLarge: String
    let tooLong: String
    let notDownloaded: String
    let notAFile: String
    let protectedPDF: String
    let leftAlone: String
    let unsupported: String
    let conversionOff: String
    let alreadyOptimized: String
    let diskSpace: String
    let cannotWrite: String
    let folderUnavailable: String
    let unreadable: String
    let noVideo: String

    static func localized(_ language: AppLanguage) -> FileOptimizerStrings {
        switch language {
        case .enUS: return .enUS
        case .ptBR: return .ptBR
        case .tr: return .tr
        case .ru: return .ru
        case .es: return .es
        case .sk: return .sk
        case .de: return .de
        case .fr: return .fr
        case .it: return .it
        case .ja: return .ja
        case .ko: return .ko
        case .zhHans: return .zhHans
        case .zhTW: return .zhTW
        case .zhHK: return .zhHK
        case .uk: return .uk
        }
    }

    func reason(_ reason: FileOptimizerSupport.SkipReason) -> String {
        switch reason {
        case .notSmaller: return notSmaller
        case .tooLarge: return tooLarge
        case .tooLong: return tooLong
        case .notDownloaded: return notDownloaded
        case .notAFile: return notAFile
        case .protected: return protectedPDF
        case .leftAlone: return leftAlone
        case .unsupported: return unsupported
        case .conversionOff: return conversionOff
        case .alreadyOptimized: return alreadyOptimized
        case .diskSpace: return diskSpace
        case .cannotWrite: return cannotWrite
        case .folderUnavailable: return folderUnavailable
        case .unreadable: return unreadable
        case .noVideo: return noVideo
        }
    }
}

extension FeatureStrings {
    static func fileOptimizer(_ language: AppLanguage) -> FileOptimizerStrings {
        FileOptimizerStrings.localized(language)
    }
}

extension FileOptimizerStrings {
    static let enUS = FileOptimizerStrings(
        title: "File optimizer",
        hubDescription: "Make images, videos and PDFs smaller",
        pageCaption: "Pick or drop images, videos and PDFs to save smaller copies. Uses the same rules as the Clipboard optimizer. Media tools is for converting one file exactly the way you want.",
        dropPrompt: "Drop images, videos or PDFs here",
        chooseFiles: "Choose Files…",
        queueHeader: "Files",
        cancelAll: "Cancel All",
        clearFinished: "Clear Finished",
        reveal: "Show in Finder",
        cancel: "Cancel",
        queued: "Waiting",
        working: "Optimizing…",
        cancelled: "Cancelled",
        failedFormat: "Failed: %@",
        sizeChangeFormat: "%@ → %@",
        savedFormat: "Saved %@ in total",
        outputHeader: "Output",
        outputMode: "Save to",
        outputBeside: "Next to the original",
        outputFolder: "Folder",
        chooseFolder: "Choose Folder…",
        noFolder: "No folder chosen",
        outputCaption: "Originals are never changed. Each result is saved as “name (optimized)” and never replaces an existing file.",
        optionsHeader: "Options",
        optionsShared: "These options also apply to the Clipboard optimizer.",
        imagesHeader: "Images",
        videosHeader: "Videos",
        pdfsHeader: "PDFs",
        convertCaption: "HEIC, WebP, AVIF and BMP files become JPEG, or PNG when they have transparency.",
        clipboardLink: "Format, quality and size options for copied files are on the File optimizer page.",
        openPage: "Open File Optimizer",
        notSmaller: "Saved under 5%. No copy was kept.",
        tooLarge: "Larger than the size limit",
        tooLong: "Longer than the duration limit",
        notDownloaded: "Not downloaded from iCloud",
        notAFile: "Not a file",
        protectedPDF: "Signed, encrypted or protected PDF, left as is",
        leftAlone: "HDR, animated or deep-color image, left as is",
        unsupported: "This file type is not supported",
        conversionOff: "Converting HEIC, WebP, AVIF and BMP is off",
        alreadyOptimized: "Already optimized",
        diskSpace: "Not enough disk space",
        cannotWrite: "Can’t write there. Choose an output folder.",
        folderUnavailable: "Output folder not available",
        unreadable: "Couldn’t read the file",
        noVideo: "No video track"
    )

    static let ptBR = FileOptimizerStrings(
        title: "Otimizador de arquivos",
        hubDescription: "Deixe imagens, vídeos e PDFs menores",
        pageCaption: "Escolha ou solte imagens, vídeos e PDFs para salvar cópias menores. Usa as mesmas regras do otimizador da área de transferência. As ferramentas de mídia servem para converter um arquivo exatamente como você quiser.",
        dropPrompt: "Solte imagens, vídeos ou PDFs aqui",
        chooseFiles: "Escolher arquivos…",
        queueHeader: "Arquivos",
        cancelAll: "Cancelar tudo",
        clearFinished: "Limpar concluídos",
        reveal: "Mostrar no Finder",
        cancel: "Cancelar",
        queued: "Aguardando",
        working: "Otimizando…",
        cancelled: "Cancelado",
        failedFormat: "Falhou: %@",
        sizeChangeFormat: "%@ → %@",
        savedFormat: "%@ economizados no total",
        outputHeader: "Saída",
        outputMode: "Salvar em",
        outputBeside: "Ao lado do original",
        outputFolder: "Pasta",
        chooseFolder: "Escolher pasta…",
        noFolder: "Nenhuma pasta escolhida",
        outputCaption: "Os originais nunca são alterados. Cada resultado é salvo como “nome (optimized)” e nunca substitui um arquivo existente.",
        optionsHeader: "Opções",
        optionsShared: "Estas opções também valem para o otimizador da área de transferência.",
        imagesHeader: "Imagens",
        videosHeader: "Vídeos",
        pdfsHeader: "PDFs",
        convertCaption: "Arquivos HEIC, WebP, AVIF e BMP viram JPEG, ou PNG quando têm transparência.",
        clipboardLink: "As opções de formato, qualidade e tamanho dos arquivos copiados ficam na página do otimizador de arquivos.",
        openPage: "Abrir otimizador de arquivos",
        notSmaller: "Não ficou pelo menos 5% menor, nenhuma cópia foi salva",
        tooLarge: "Maior que o limite de tamanho",
        tooLong: "Mais longo que o limite de duração",
        notDownloaded: "Não baixado do iCloud",
        notAFile: "Não é um arquivo",
        protectedPDF: "PDF assinado, criptografado ou protegido, mantido como está",
        leftAlone: "Imagem HDR, animada ou com cor profunda, mantida como está",
        unsupported: "Este tipo de arquivo não é compatível",
        conversionOff: "A conversão de HEIC, WebP, AVIF e BMP está desativada",
        alreadyOptimized: "Já otimizado",
        diskSpace: "Espaço em disco insuficiente",
        cannotWrite: "Não é possível gravar ali. Escolha uma pasta de saída.",
        folderUnavailable: "Pasta de saída indisponível",
        unreadable: "Não foi possível ler o arquivo",
        noVideo: "Sem faixa de vídeo"
    )

    static let tr = FileOptimizerStrings(
        title: "Dosya iyileştirici",
        hubDescription: "Görselleri, videoları ve PDF’leri küçültün",
        pageCaption: "Daha küçük kopyalar kaydetmek için görsel, video ve PDF seçin ya da bırakın. Pano iyileştiricisiyle aynı kuralları kullanır. Medya araçları tek bir dosyayı tam istediğiniz gibi dönüştürmek içindir.",
        dropPrompt: "Görselleri, videoları veya PDF’leri buraya bırakın",
        chooseFiles: "Dosya seç…",
        queueHeader: "Dosyalar",
        cancelAll: "Tümünü iptal et",
        clearFinished: "Bitenleri temizle",
        reveal: "Finder’da göster",
        cancel: "İptal",
        queued: "Bekliyor",
        working: "İyileştiriliyor…",
        cancelled: "İptal edildi",
        failedFormat: "Başarısız: %@",
        sizeChangeFormat: "%@ → %@",
        savedFormat: "Toplam %@ kazanıldı",
        outputHeader: "Çıktı",
        outputMode: "Kaydetme yeri",
        outputBeside: "Orijinalin yanına",
        outputFolder: "Klasör",
        chooseFolder: "Klasör seç…",
        noFolder: "Klasör seçilmedi",
        outputCaption: "Orijinaller asla değiştirilmez. Her sonuç “ad (optimized)” olarak kaydedilir ve var olan bir dosyanın yerine geçmez.",
        optionsHeader: "Seçenekler",
        optionsShared: "Bu seçenekler Pano iyileştiricisi için de geçerlidir.",
        imagesHeader: "Görseller",
        videosHeader: "Videolar",
        pdfsHeader: "PDF’ler",
        convertCaption: "HEIC, WebP, AVIF ve BMP dosyaları JPEG’e, saydamlık varsa PNG’ye dönüşür.",
        clipboardLink: "Kopyalanan dosyaların biçim, kalite ve boyut seçenekleri Dosya iyileştirici sayfasındadır.",
        openPage: "Dosya iyileştiriciyi aç",
        notSmaller: "En az %5 küçülmedi, kopya kaydedilmedi",
        tooLarge: "Boyut sınırından büyük",
        tooLong: "Süre sınırından uzun",
        notDownloaded: "iCloud’dan indirilmemiş",
        notAFile: "Dosya değil",
        protectedPDF: "İmzalı, şifreli veya korumalı PDF, olduğu gibi bırakıldı",
        leftAlone: "HDR, hareketli veya derin renkli görsel, olduğu gibi bırakıldı",
        unsupported: "Bu dosya türü desteklenmiyor",
        conversionOff: "HEIC, WebP, AVIF ve BMP dönüştürme kapalı",
        alreadyOptimized: "Zaten iyileştirilmiş",
        diskSpace: "Yeterli disk alanı yok",
        cannotWrite: "Oraya yazılamıyor. Bir çıktı klasörü seçin.",
        folderUnavailable: "Çıktı klasörü kullanılamıyor",
        unreadable: "Dosya okunamadı",
        noVideo: "Video izi yok"
    )

    static let ru = FileOptimizerStrings(
        title: "Оптимизатор файлов",
        hubDescription: "Уменьшает изображения, видео и PDF",
        pageCaption: "Выберите или перетащите изображения, видео и PDF, чтобы сохранить уменьшенные копии. Работает по тем же правилам, что и оптимизатор буфера обмена. Медиаинструменты нужны, чтобы преобразовать один файл именно так, как вам нужно.",
        dropPrompt: "Перетащите сюда изображения, видео или PDF",
        chooseFiles: "Выбрать файлы…",
        queueHeader: "Файлы",
        cancelAll: "Отменить все",
        clearFinished: "Убрать завершённые",
        reveal: "Показать в Finder",
        cancel: "Отменить",
        queued: "Ожидает",
        working: "Оптимизация…",
        cancelled: "Отменено",
        failedFormat: "Ошибка: %@",
        sizeChangeFormat: "%@ → %@",
        savedFormat: "Всего сэкономлено %@",
        outputHeader: "Сохранение",
        outputMode: "Сохранять",
        outputBeside: "Рядом с оригиналом",
        outputFolder: "В папку",
        chooseFolder: "Выбрать папку…",
        noFolder: "Папка не выбрана",
        outputCaption: "Оригиналы никогда не изменяются. Каждый результат сохраняется как «имя (optimized)» и никогда не заменяет существующий файл.",
        optionsHeader: "Параметры",
        optionsShared: "Эти параметры действуют и для оптимизатора буфера обмена.",
        imagesHeader: "Изображения",
        videosHeader: "Видео",
        pdfsHeader: "PDF",
        convertCaption: "Файлы HEIC, WebP, AVIF и BMP становятся JPEG, а при наличии прозрачности, PNG.",
        clipboardLink: "Параметры формата, качества и размера для скопированных файлов находятся на странице оптимизатора файлов.",
        openPage: "Открыть оптимизатор файлов",
        notSmaller: "Меньше чем на 5%, копия не сохранена",
        tooLarge: "Больше ограничения по размеру",
        tooLong: "Длиннее ограничения по длительности",
        notDownloaded: "Не загружен из iCloud",
        notAFile: "Не файл",
        protectedPDF: "Подписанный, зашифрованный или защищённый PDF оставлен как есть",
        leftAlone: "HDR, анимированное изображение или изображение с глубоким цветом оставлено как есть",
        unsupported: "Этот тип файла не поддерживается",
        conversionOff: "Преобразование HEIC, WebP, AVIF и BMP выключено",
        alreadyOptimized: "Уже оптимизирован",
        diskSpace: "Недостаточно места на диске",
        cannotWrite: "Туда нельзя записать. Выберите папку для сохранения.",
        folderUnavailable: "Папка для сохранения недоступна",
        unreadable: "Не удалось прочитать файл",
        noVideo: "Нет видеодорожки"
    )

    static let es = FileOptimizerStrings(
        title: "Optimizador de archivos",
        hubDescription: "Reduce imágenes, vídeos y PDF",
        pageCaption: "Elige o suelta imágenes, vídeos y PDF para guardar copias más pequeñas. Usa las mismas reglas que el optimizador del portapapeles. Las herramientas multimedia sirven para convertir un archivo exactamente como quieras.",
        dropPrompt: "Suelta aquí imágenes, vídeos o PDF",
        chooseFiles: "Elegir archivos…",
        queueHeader: "Archivos",
        cancelAll: "Cancelar todo",
        clearFinished: "Borrar terminados",
        reveal: "Mostrar en Finder",
        cancel: "Cancelar",
        queued: "En espera",
        working: "Optimizando…",
        cancelled: "Cancelado",
        failedFormat: "Error: %@",
        sizeChangeFormat: "%@ → %@",
        savedFormat: "%@ ahorrados en total",
        outputHeader: "Salida",
        outputMode: "Guardar en",
        outputBeside: "Junto al original",
        outputFolder: "Carpeta",
        chooseFolder: "Elegir carpeta…",
        noFolder: "Ninguna carpeta elegida",
        outputCaption: "Los originales nunca se modifican. Cada resultado se guarda como «nombre (optimized)» y nunca reemplaza un archivo existente.",
        optionsHeader: "Opciones",
        optionsShared: "Estas opciones también se aplican al optimizador del portapapeles.",
        imagesHeader: "Imágenes",
        videosHeader: "Vídeos",
        pdfsHeader: "PDF",
        convertCaption: "Los archivos HEIC, WebP, AVIF y BMP pasan a JPEG, o a PNG si tienen transparencia.",
        clipboardLink: "Las opciones de formato, calidad y tamaño de los archivos copiados están en la página del optimizador de archivos.",
        openPage: "Abrir optimizador de archivos",
        notSmaller: "No es al menos un 5 % más pequeño, no se guardó ninguna copia",
        tooLarge: "Supera el límite de tamaño",
        tooLong: "Supera el límite de duración",
        notDownloaded: "No descargado de iCloud",
        notAFile: "No es un archivo",
        protectedPDF: "PDF firmado, cifrado o protegido, se deja como está",
        leftAlone: "Imagen HDR, animada o de color profundo, se deja como está",
        unsupported: "Este tipo de archivo no es compatible",
        conversionOff: "La conversión de HEIC, WebP, AVIF y BMP está desactivada",
        alreadyOptimized: "Ya optimizado",
        diskSpace: "No hay suficiente espacio en disco",
        cannotWrite: "No se puede escribir ahí. Elige una carpeta de salida.",
        folderUnavailable: "Carpeta de salida no disponible",
        unreadable: "No se pudo leer el archivo",
        noVideo: "Sin pista de vídeo"
    )

    static let sk = FileOptimizerStrings(
        title: "Optimalizátor súborov",
        hubDescription: "Zmenšuje obrázky, videá a PDF",
        pageCaption: "Vyberte alebo presuňte obrázky, videá a PDF a uložte ich menšie kópie. Používa rovnaké pravidlá ako optimalizátor schránky. Nástroje médií slúžia na prevod jedného súboru presne podľa vašich predstáv.",
        dropPrompt: "Presuňte sem obrázky, videá alebo PDF",
        chooseFiles: "Vybrať súbory…",
        queueHeader: "Súbory",
        cancelAll: "Zrušiť všetko",
        clearFinished: "Vymazať dokončené",
        reveal: "Zobraziť vo Finderi",
        cancel: "Zrušiť",
        queued: "Čaká",
        working: "Optimalizuje sa…",
        cancelled: "Zrušené",
        failedFormat: "Zlyhalo: %@",
        sizeChangeFormat: "%@ → %@",
        savedFormat: "Celkovo ušetrené %@",
        outputHeader: "Výstup",
        outputMode: "Uložiť do",
        outputBeside: "Vedľa originálu",
        outputFolder: "Priečinok",
        chooseFolder: "Vybrať priečinok…",
        noFolder: "Nie je vybraný priečinok",
        outputCaption: "Originály sa nikdy nemenia. Každý výsledok sa uloží ako „názov (optimized)“ a nikdy nenahradí existujúci súbor.",
        optionsHeader: "Možnosti",
        optionsShared: "Tieto možnosti platia aj pre optimalizátor schránky.",
        imagesHeader: "Obrázky",
        videosHeader: "Videá",
        pdfsHeader: "PDF",
        convertCaption: "Súbory HEIC, WebP, AVIF a BMP sa zmenia na JPEG, alebo na PNG, ak majú priehľadnosť.",
        clipboardLink: "Možnosti formátu, kvality a veľkosti pre skopírované súbory sú na stránke optimalizátora súborov.",
        openPage: "Otvoriť optimalizátor súborov",
        notSmaller: "Nie je aspoň o 5 % menší, kópia sa neuložila",
        tooLarge: "Väčší ako limit veľkosti",
        tooLong: "Dlhší ako limit dĺžky",
        notDownloaded: "Nestiahnuté z iCloudu",
        notAFile: "Nie je súbor",
        protectedPDF: "Podpísané, šifrované alebo chránené PDF, ponechané bez zmeny",
        leftAlone: "HDR, animovaný obrázok alebo obrázok s hlbokou farbou, ponechaný bez zmeny",
        unsupported: "Tento typ súboru nie je podporovaný",
        conversionOff: "Prevod HEIC, WebP, AVIF a BMP je vypnutý",
        alreadyOptimized: "Už optimalizované",
        diskSpace: "Nedostatok miesta na disku",
        cannotWrite: "Sem sa nedá zapisovať. Vyberte výstupný priečinok.",
        folderUnavailable: "Výstupný priečinok nie je dostupný",
        unreadable: "Súbor sa nepodarilo prečítať",
        noVideo: "Bez video stopy"
    )

    static let de = FileOptimizerStrings(
        title: "Dateioptimierer",
        hubDescription: "Macht Bilder, Videos und PDFs kleiner",
        pageCaption: "Wähle Bilder, Videos und PDFs aus oder lege sie hier ab, um kleinere Kopien zu sichern. Es gelten dieselben Regeln wie beim Zwischenablage-Optimierer. Die Medienwerkzeuge sind dafür da, eine Datei genau nach deinen Wünschen umzuwandeln.",
        dropPrompt: "Bilder, Videos oder PDFs hier ablegen",
        chooseFiles: "Dateien auswählen …",
        queueHeader: "Dateien",
        cancelAll: "Alle abbrechen",
        clearFinished: "Erledigte entfernen",
        reveal: "Im Finder zeigen",
        cancel: "Abbrechen",
        queued: "Wartet",
        working: "Wird optimiert …",
        cancelled: "Abgebrochen",
        failedFormat: "Fehlgeschlagen: %@",
        sizeChangeFormat: "%@ → %@",
        savedFormat: "Insgesamt %@ gespart",
        outputHeader: "Ausgabe",
        outputMode: "Sichern in",
        outputBeside: "Neben dem Original",
        outputFolder: "Ordner",
        chooseFolder: "Ordner auswählen …",
        noFolder: "Kein Ordner ausgewählt",
        outputCaption: "Originale werden nie verändert. Jedes Ergebnis wird als „Name (optimized)“ gesichert und ersetzt nie eine vorhandene Datei.",
        optionsHeader: "Optionen",
        optionsShared: "Diese Optionen gelten auch für den Zwischenablage-Optimierer.",
        imagesHeader: "Bilder",
        videosHeader: "Videos",
        pdfsHeader: "PDFs",
        convertCaption: "HEIC-, WebP-, AVIF- und BMP-Dateien werden zu JPEG, bei Transparenz zu PNG.",
        clipboardLink: "Format-, Qualitäts- und Größenoptionen für kopierte Dateien findest du auf der Seite des Dateioptimierers.",
        openPage: "Dateioptimierer öffnen",
        notSmaller: "Nicht mindestens 5 % kleiner, keine Kopie gesichert",
        tooLarge: "Größer als das Größenlimit",
        tooLong: "Länger als das Dauerlimit",
        notDownloaded: "Nicht aus iCloud geladen",
        notAFile: "Keine Datei",
        protectedPDF: "Signiertes, verschlüsseltes oder geschütztes PDF, unverändert gelassen",
        leftAlone: "HDR-, animiertes oder Bild mit hoher Farbtiefe, unverändert gelassen",
        unsupported: "Dieser Dateityp wird nicht unterstützt",
        conversionOff: "Umwandeln von HEIC, WebP, AVIF und BMP ist aus",
        alreadyOptimized: "Bereits optimiert",
        diskSpace: "Nicht genug Speicherplatz",
        cannotWrite: "Dort kann nicht geschrieben werden. Wähle einen Ausgabeordner.",
        folderUnavailable: "Ausgabeordner nicht verfügbar",
        unreadable: "Datei konnte nicht gelesen werden",
        noVideo: "Keine Videospur"
    )

    static let fr = FileOptimizerStrings(
        title: "Optimiseur de fichiers",
        hubDescription: "Réduit la taille des images, vidéos et PDF",
        pageCaption: "Choisissez ou déposez des images, vidéos et PDF pour en enregistrer des copies plus légères. Les règles sont celles de l’optimiseur du presse-papiers. Les outils multimédias servent à convertir un fichier exactement comme vous le souhaitez.",
        dropPrompt: "Déposez ici des images, vidéos ou PDF",
        chooseFiles: "Choisir des fichiers…",
        queueHeader: "Fichiers",
        cancelAll: "Tout annuler",
        clearFinished: "Effacer les terminés",
        reveal: "Afficher dans le Finder",
        cancel: "Annuler",
        queued: "En attente",
        working: "Optimisation…",
        cancelled: "Annulé",
        failedFormat: "Échec : %@",
        sizeChangeFormat: "%@ → %@",
        savedFormat: "%@ économisés au total",
        outputHeader: "Sortie",
        outputMode: "Enregistrer",
        outputBeside: "À côté de l’original",
        outputFolder: "Dossier",
        chooseFolder: "Choisir un dossier…",
        noFolder: "Aucun dossier choisi",
        outputCaption: "Les originaux ne sont jamais modifiés. Chaque résultat est enregistré sous « nom (optimized) » et ne remplace jamais un fichier existant.",
        optionsHeader: "Options",
        optionsShared: "Ces options s’appliquent aussi à l’optimiseur du presse-papiers.",
        imagesHeader: "Images",
        videosHeader: "Vidéos",
        pdfsHeader: "PDF",
        convertCaption: "Les fichiers HEIC, WebP, AVIF et BMP deviennent des JPEG, ou des PNG s’ils ont de la transparence.",
        clipboardLink: "Les options de format, de qualité et de taille des fichiers copiés se trouvent sur la page de l’optimiseur de fichiers.",
        openPage: "Ouvrir l’optimiseur de fichiers",
        notSmaller: "Pas au moins 5 % plus petit, aucune copie enregistrée",
        tooLarge: "Dépasse la taille limite",
        tooLong: "Dépasse la durée limite",
        notDownloaded: "Non téléchargé depuis iCloud",
        notAFile: "Pas un fichier",
        protectedPDF: "PDF signé, chiffré ou protégé, laissé tel quel",
        leftAlone: "Image HDR, animée ou en couleurs profondes, laissée telle quelle",
        unsupported: "Ce type de fichier n’est pas pris en charge",
        conversionOff: "La conversion HEIC, WebP, AVIF et BMP est désactivée",
        alreadyOptimized: "Déjà optimisé",
        diskSpace: "Espace disque insuffisant",
        cannotWrite: "Impossible d’écrire à cet endroit. Choisissez un dossier de sortie.",
        folderUnavailable: "Dossier de sortie indisponible",
        unreadable: "Impossible de lire le fichier",
        noVideo: "Aucune piste vidéo"
    )

    static let it = FileOptimizerStrings(
        title: "Ottimizzatore di file",
        hubDescription: "Rende più leggeri immagini, video e PDF",
        pageCaption: "Scegli o trascina immagini, video e PDF per salvarne copie più leggere. Usa le stesse regole dell’ottimizzatore degli appunti. Gli strumenti multimediali servono a convertire un file esattamente come vuoi.",
        dropPrompt: "Trascina qui immagini, video o PDF",
        chooseFiles: "Scegli file…",
        queueHeader: "File",
        cancelAll: "Annulla tutto",
        clearFinished: "Rimuovi completati",
        reveal: "Mostra nel Finder",
        cancel: "Annulla",
        queued: "In attesa",
        working: "Ottimizzazione…",
        cancelled: "Annullato",
        failedFormat: "Non riuscito: %@",
        sizeChangeFormat: "%@ → %@",
        savedFormat: "%@ risparmiati in totale",
        outputHeader: "Uscita",
        outputMode: "Salva in",
        outputBeside: "Accanto all’originale",
        outputFolder: "Cartella",
        chooseFolder: "Scegli cartella…",
        noFolder: "Nessuna cartella scelta",
        outputCaption: "Gli originali non vengono mai modificati. Ogni risultato viene salvato come “nome (optimized)” e non sostituisce mai un file esistente.",
        optionsHeader: "Opzioni",
        optionsShared: "Queste opzioni valgono anche per l’ottimizzatore degli appunti.",
        imagesHeader: "Immagini",
        videosHeader: "Video",
        pdfsHeader: "PDF",
        convertCaption: "I file HEIC, WebP, AVIF e BMP diventano JPEG, o PNG se hanno trasparenza.",
        clipboardLink: "Le opzioni di formato, qualità e dimensione per i file copiati sono nella pagina dell’ottimizzatore di file.",
        openPage: "Apri ottimizzatore di file",
        notSmaller: "Non è più piccolo di almeno il 5%, nessuna copia salvata",
        tooLarge: "Supera il limite di dimensione",
        tooLong: "Supera il limite di durata",
        notDownloaded: "Non scaricato da iCloud",
        notAFile: "Non è un file",
        protectedPDF: "PDF firmato, cifrato o protetto, lasciato così com’è",
        leftAlone: "Immagine HDR, animata o a colori profondi, lasciata così com’è",
        unsupported: "Questo tipo di file non è supportato",
        conversionOff: "La conversione di HEIC, WebP, AVIF e BMP è disattivata",
        alreadyOptimized: "Già ottimizzato",
        diskSpace: "Spazio su disco insufficiente",
        cannotWrite: "Impossibile scrivere lì. Scegli una cartella di uscita.",
        folderUnavailable: "Cartella di uscita non disponibile",
        unreadable: "Impossibile leggere il file",
        noVideo: "Nessuna traccia video"
    )

    static let ja = FileOptimizerStrings(
        title: "ファイル最適化",
        hubDescription: "画像、ビデオ、PDFを小さくします",
        pageCaption: "画像、ビデオ、PDFを選択またはドロップすると、小さくしたコピーを保存します。クリップボード最適化と同じルールを使います。1つのファイルを思いどおりに変換するにはメディアツールを使います。",
        dropPrompt: "画像、ビデオ、PDFをここにドロップ",
        chooseFiles: "ファイルを選択…",
        queueHeader: "ファイル",
        cancelAll: "すべてキャンセル",
        clearFinished: "完了したものを消去",
        reveal: "Finderで表示",
        cancel: "キャンセル",
        queued: "待機中",
        working: "最適化中…",
        cancelled: "キャンセル済み",
        failedFormat: "失敗: %@",
        sizeChangeFormat: "%@ → %@",
        savedFormat: "合計 %@ 削減",
        outputHeader: "出力",
        outputMode: "保存先",
        outputBeside: "元のファイルの横",
        outputFolder: "フォルダ",
        chooseFolder: "フォルダを選択…",
        noFolder: "フォルダが選択されていません",
        outputCaption: "元のファイルは変更されません。結果は「名前 (optimized)」として保存され、既存のファイルを置き換えることはありません。",
        optionsHeader: "オプション",
        optionsShared: "これらのオプションはクリップボード最適化にも適用されます。",
        imagesHeader: "画像",
        videosHeader: "ビデオ",
        pdfsHeader: "PDF",
        convertCaption: "HEIC、WebP、AVIF、BMPファイルはJPEGに、透明部分がある場合はPNGになります。",
        clipboardLink: "コピーしたファイルの形式、品質、サイズのオプションはファイル最適化のページにあります。",
        openPage: "ファイル最適化を開く",
        notSmaller: "5%以上小さくならないため、コピーは保存されませんでした",
        tooLarge: "サイズの上限を超えています",
        tooLong: "長さの上限を超えています",
        notDownloaded: "iCloudからダウンロードされていません",
        notAFile: "ファイルではありません",
        protectedPDF: "署名、暗号化、または保護されたPDFのため、そのままにしました",
        leftAlone: "HDR、アニメーション、または高色深度の画像のため、そのままにしました",
        unsupported: "このファイル形式には対応していません",
        conversionOff: "HEIC、WebP、AVIF、BMPの変換はオフです",
        alreadyOptimized: "最適化済み",
        diskSpace: "ディスクの空き容量が足りません",
        cannotWrite: "そこには書き込めません。出力フォルダを選択してください。",
        folderUnavailable: "出力フォルダを使用できません",
        unreadable: "ファイルを読み込めませんでした",
        noVideo: "ビデオトラックがありません"
    )

    static let ko = FileOptimizerStrings(
        title: "파일 최적화",
        hubDescription: "이미지, 비디오, PDF를 더 작게 만듭니다",
        pageCaption: "이미지, 비디오, PDF를 선택하거나 끌어다 놓으면 더 작은 사본을 저장합니다. 클립보드 최적화와 같은 규칙을 사용합니다. 파일 하나를 원하는 대로 정확히 변환하려면 미디어 도구를 사용하세요.",
        dropPrompt: "이미지, 비디오 또는 PDF를 여기에 놓으세요",
        chooseFiles: "파일 선택…",
        queueHeader: "파일",
        cancelAll: "모두 취소",
        clearFinished: "완료 항목 지우기",
        reveal: "Finder에서 보기",
        cancel: "취소",
        queued: "대기 중",
        working: "최적화 중…",
        cancelled: "취소됨",
        failedFormat: "실패: %@",
        sizeChangeFormat: "%@ → %@",
        savedFormat: "총 %@ 절약",
        outputHeader: "출력",
        outputMode: "저장 위치",
        outputBeside: "원본 옆",
        outputFolder: "폴더",
        chooseFolder: "폴더 선택…",
        noFolder: "선택한 폴더 없음",
        outputCaption: "원본은 절대 변경되지 않습니다. 결과는 ‘이름 (optimized)’으로 저장되며 기존 파일을 대체하지 않습니다.",
        optionsHeader: "옵션",
        optionsShared: "이 옵션은 클립보드 최적화에도 적용됩니다.",
        imagesHeader: "이미지",
        videosHeader: "비디오",
        pdfsHeader: "PDF",
        convertCaption: "HEIC, WebP, AVIF, BMP 파일은 JPEG로, 투명도가 있으면 PNG로 바뀝니다.",
        clipboardLink: "복사한 파일의 형식, 품질, 크기 옵션은 파일 최적화 페이지에 있습니다.",
        openPage: "파일 최적화 열기",
        notSmaller: "5% 이상 작아지지 않아 사본을 저장하지 않았습니다",
        tooLarge: "크기 제한보다 큽니다",
        tooLong: "길이 제한보다 깁니다",
        notDownloaded: "iCloud에서 다운로드되지 않았습니다",
        notAFile: "파일이 아닙니다",
        protectedPDF: "서명, 암호화 또는 보호된 PDF라 그대로 두었습니다",
        leftAlone: "HDR, 애니메이션 또는 고색심도 이미지라 그대로 두었습니다",
        unsupported: "지원하지 않는 파일 형식입니다",
        conversionOff: "HEIC, WebP, AVIF, BMP 변환이 꺼져 있습니다",
        alreadyOptimized: "이미 최적화됨",
        diskSpace: "디스크 공간이 부족합니다",
        cannotWrite: "그곳에 쓸 수 없습니다. 출력 폴더를 선택하세요.",
        folderUnavailable: "출력 폴더를 사용할 수 없습니다",
        unreadable: "파일을 읽을 수 없습니다",
        noVideo: "비디오 트랙이 없습니다"
    )

    static let zhHans = FileOptimizerStrings(
        title: "文件优化",
        hubDescription: "缩小图像、视频和 PDF",
        pageCaption: "选择或拖入图像、视频和 PDF，即可保存更小的副本。使用与剪贴板优化相同的规则。若要按你的方式精确转换单个文件，请使用媒体工具。",
        dropPrompt: "将图像、视频或 PDF 拖到这里",
        chooseFiles: "选择文件…",
        queueHeader: "文件",
        cancelAll: "全部取消",
        clearFinished: "清除已完成",
        reveal: "在访达中显示",
        cancel: "取消",
        queued: "等待中",
        working: "正在优化…",
        cancelled: "已取消",
        failedFormat: "失败：%@",
        sizeChangeFormat: "%@ → %@",
        savedFormat: "共节省 %@",
        outputHeader: "输出",
        outputMode: "保存到",
        outputBeside: "原文件旁边",
        outputFolder: "文件夹",
        chooseFolder: "选择文件夹…",
        noFolder: "未选择文件夹",
        outputCaption: "原文件永远不会被修改。每个结果都保存为“名称 (optimized)”，不会替换已有文件。",
        optionsHeader: "选项",
        optionsShared: "这些选项同样适用于剪贴板优化。",
        imagesHeader: "图像",
        videosHeader: "视频",
        pdfsHeader: "PDF",
        convertCaption: "HEIC、WebP、AVIF 和 BMP 文件会转为 JPEG，有透明度时转为 PNG。",
        clipboardLink: "已拷贝文件的格式、质量和大小选项位于文件优化页面。",
        openPage: "打开文件优化",
        notSmaller: "缩小不足 5%，未保存副本",
        tooLarge: "超过大小限制",
        tooLong: "超过时长限制",
        notDownloaded: "未从 iCloud 下载",
        notAFile: "不是文件",
        protectedPDF: "已签名、加密或受保护的 PDF，保持原样",
        leftAlone: "HDR、动画或高色深图像，保持原样",
        unsupported: "不支持此文件类型",
        conversionOff: "HEIC、WebP、AVIF 和 BMP 转换已关闭",
        alreadyOptimized: "已优化",
        diskSpace: "磁盘空间不足",
        cannotWrite: "无法写入该位置。请选择输出文件夹。",
        folderUnavailable: "输出文件夹不可用",
        unreadable: "无法读取文件",
        noVideo: "没有视频轨道"
    )

    static let zhTW = FileOptimizerStrings(
        title: "檔案最佳化",
        hubDescription: "縮小影像、影片和 PDF",
        pageCaption: "選擇或拖入影像、影片和 PDF，即可儲存較小的副本。使用與剪貼簿最佳化相同的規則。若要依你的方式精確轉換單一檔案，請使用媒體工具。",
        dropPrompt: "將影像、影片或 PDF 拖到這裡",
        chooseFiles: "選擇檔案…",
        queueHeader: "檔案",
        cancelAll: "全部取消",
        clearFinished: "清除已完成",
        reveal: "在 Finder 中顯示",
        cancel: "取消",
        queued: "等待中",
        working: "正在最佳化…",
        cancelled: "已取消",
        failedFormat: "失敗：%@",
        sizeChangeFormat: "%@ → %@",
        savedFormat: "共節省 %@",
        outputHeader: "輸出",
        outputMode: "儲存到",
        outputBeside: "原始檔案旁邊",
        outputFolder: "檔案夾",
        chooseFolder: "選擇檔案夾…",
        noFolder: "未選擇檔案夾",
        outputCaption: "原始檔案永遠不會被修改。每個結果都會儲存為「名稱 (optimized)」，不會取代既有檔案。",
        optionsHeader: "選項",
        optionsShared: "這些選項也適用於剪貼簿最佳化。",
        imagesHeader: "影像",
        videosHeader: "影片",
        pdfsHeader: "PDF",
        convertCaption: "HEIC、WebP、AVIF 和 BMP 檔案會轉為 JPEG，有透明度時轉為 PNG。",
        clipboardLink: "拷貝檔案的格式、品質和大小選項位於檔案最佳化頁面。",
        openPage: "打開檔案最佳化",
        notSmaller: "縮小不到 5%，未儲存副本",
        tooLarge: "超過大小限制",
        tooLong: "超過長度限制",
        notDownloaded: "未從 iCloud 下載",
        notAFile: "不是檔案",
        protectedPDF: "已簽署、加密或受保護的 PDF，保持原樣",
        leftAlone: "HDR、動畫或高色深影像，保持原樣",
        unsupported: "不支援此檔案類型",
        conversionOff: "HEIC、WebP、AVIF 和 BMP 轉換已關閉",
        alreadyOptimized: "已最佳化",
        diskSpace: "磁碟空間不足",
        cannotWrite: "無法寫入該位置。請選擇輸出檔案夾。",
        folderUnavailable: "輸出檔案夾無法使用",
        unreadable: "無法讀取檔案",
        noVideo: "沒有影片軌"
    )

    static let zhHK = FileOptimizerStrings(
        title: "檔案優化",
        hubDescription: "縮小影像、影片和 PDF",
        pageCaption: "選擇或拖入影像、影片和 PDF，即可儲存較細的副本。使用與剪貼板優化相同的規則。如要按你的方式準確轉換單一檔案，請使用媒體工具。",
        dropPrompt: "將影像、影片或 PDF 拖到這裏",
        chooseFiles: "選擇檔案…",
        queueHeader: "檔案",
        cancelAll: "全部取消",
        clearFinished: "清除已完成",
        reveal: "在 Finder 中顯示",
        cancel: "取消",
        queued: "等待中",
        working: "正在優化…",
        cancelled: "已取消",
        failedFormat: "失敗：%@",
        sizeChangeFormat: "%@ → %@",
        savedFormat: "合共節省 %@",
        outputHeader: "輸出",
        outputMode: "儲存到",
        outputBeside: "原檔案旁邊",
        outputFolder: "檔案夾",
        chooseFolder: "選擇檔案夾…",
        noFolder: "未選擇檔案夾",
        outputCaption: "原檔案永遠不會被修改。每個結果都會儲存為「名稱 (optimized)」，不會取代現有檔案。",
        optionsHeader: "選項",
        optionsShared: "這些選項亦適用於剪貼板優化。",
        imagesHeader: "影像",
        videosHeader: "影片",
        pdfsHeader: "PDF",
        convertCaption: "HEIC、WebP、AVIF 和 BMP 檔案會轉為 JPEG，有透明度時轉為 PNG。",
        clipboardLink: "拷貝檔案的格式、質素和大小選項位於檔案優化頁面。",
        openPage: "打開檔案優化",
        notSmaller: "縮小不足 5%，未儲存副本",
        tooLarge: "超過大小限制",
        tooLong: "超過長度限制",
        notDownloaded: "未從 iCloud 下載",
        notAFile: "不是檔案",
        protectedPDF: "已簽署、加密或受保護的 PDF，保持原樣",
        leftAlone: "HDR、動畫或高色深影像，保持原樣",
        unsupported: "不支援此檔案類型",
        conversionOff: "HEIC、WebP、AVIF 和 BMP 轉換已關閉",
        alreadyOptimized: "已優化",
        diskSpace: "磁碟空間不足",
        cannotWrite: "無法寫入該位置。請選擇輸出檔案夾。",
        folderUnavailable: "輸出檔案夾無法使用",
        unreadable: "無法讀取檔案",
        noVideo: "沒有影片軌"
    )

    static let uk = FileOptimizerStrings(
        title: "Оптимізатор файлів",
        hubDescription: "Зменшує зображення, відео та PDF",
        pageCaption: "Виберіть або перетягніть зображення, відео та PDF, щоб зберегти менші копії. Працює за тими самими правилами, що й оптимізатор буфера обміну. Медіаінструменти потрібні, щоб перетворити один файл саме так, як вам треба.",
        dropPrompt: "Перетягніть сюди зображення, відео або PDF",
        chooseFiles: "Вибрати файли…",
        queueHeader: "Файли",
        cancelAll: "Скасувати все",
        clearFinished: "Прибрати завершені",
        reveal: "Показати у Finder",
        cancel: "Скасувати",
        queued: "Очікує",
        working: "Оптимізація…",
        cancelled: "Скасовано",
        failedFormat: "Помилка: %@",
        sizeChangeFormat: "%@ → %@",
        savedFormat: "Загалом заощаджено %@",
        outputHeader: "Збереження",
        outputMode: "Зберігати",
        outputBeside: "Поруч з оригіналом",
        outputFolder: "У папку",
        chooseFolder: "Вибрати папку…",
        noFolder: "Папку не вибрано",
        outputCaption: "Оригінали ніколи не змінюються. Кожен результат зберігається як «назва (optimized)» і ніколи не замінює наявний файл.",
        optionsHeader: "Параметри",
        optionsShared: "Ці параметри діють і для оптимізатора буфера обміну.",
        imagesHeader: "Зображення",
        videosHeader: "Відео",
        pdfsHeader: "PDF",
        convertCaption: "Файли HEIC, WebP, AVIF і BMP стають JPEG, а за наявності прозорості, PNG.",
        clipboardLink: "Параметри формату, якості й розміру для скопійованих файлів, на сторінці оптимізатора файлів.",
        openPage: "Відкрити оптимізатор файлів",
        notSmaller: "Менше ніж на 5%, копію не збережено",
        tooLarge: "Більше за обмеження розміру",
        tooLong: "Довше за обмеження тривалості",
        notDownloaded: "Не завантажено з iCloud",
        notAFile: "Не файл",
        protectedPDF: "Підписаний, зашифрований або захищений PDF залишено як є",
        leftAlone: "HDR, анімоване зображення або зображення з глибоким кольором залишено як є",
        unsupported: "Цей тип файлу не підтримується",
        conversionOff: "Перетворення HEIC, WebP, AVIF і BMP вимкнено",
        alreadyOptimized: "Уже оптимізовано",
        diskSpace: "Недостатньо місця на диску",
        cannotWrite: "Туди не можна записати. Виберіть папку для збереження.",
        folderUnavailable: "Папка для збереження недоступна",
        unreadable: "Не вдалося прочитати файл",
        noVideo: "Немає відеодоріжки"
    )
}
